#!/usr/bin/env bash
set -e

if [ -f "composer.lock" ]; then
    PHP_CS_FIXER="$(composer config bin-dir)/php-cs-fixer"

    if [ -x "$PHP_CS_FIXER" ]; then
        git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read -r line; do
            php -C -n -d date.timezone=UTC "$PHP_CS_FIXER" fix --ansi --dry-run --verbose "${line}"
        done
    fi
fi

